strains:
  - name: default
    code:
      url: https://github.com/joseverticurl/aem-eds-universaleditor-training.git
    content:
      url: https://aem-eds-universaleditor-poc.hlx.page
    condition: 
      url: '^.*$'
    headers:
      cache-control: "max-age=0, stale-while-revalidate=600, stale-if-error=86400"
metadata:
  - name: urn:adobe:aue:config:disable
    content: publish
    