strains:
  - name: default
    code:
      url: https://github.com/joseverticurl/aem-eds-universaleditor-poc.git
    content:
      url: https://main--aem-eds-universaleditor-poc--joseverticurl.aem.live
    condition:
      url: '^.*$'
    headers:
      cache-control: "max-age=0, stale-while-revalidate=600, stale-if-error=86400"
