strains:
  - name: default
    code:
      url: https://github.com/joseverticurl/aem-eds-universaleditor-poc.git
    content:
      url: https://aem-eds-universaleditor-poc.hlx.page
    condition:
      url: '^.*$'
    sidekick:
      urn:adobe:aue:config:disable:
        - publish
    headers:
      cache-control: "max-age=0, stale-while-revalidate=600, stale-if-error=86400"
